#!/bin/sh

git filter-branch --env-filter '
  GIT_AUTHOR_NAME="Nakamura, Ryotaro"
  export GIT_AUTHOR_NAME
  GIT_AUTHOR_EMAIL=nakamura.ryotaro.kzs@gmail.com
  export GIT_AUTHOR_EMAIL
  GIT_AUTHOR_DATE="Thu Jan 19 12:50:18 2017 +0900"
  export GIT_AUTHOR_DATE
  GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
  export GIT_COMMITTER_NAME
  GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
  export GIT_COMMITTER_EMAIL
  GIT_COMMITTER_DATE=$GIT_AUTHOR_DATE
  export GIT_COMMITTER_DATE
' -- --all


